import {build} from 'esbuild';
import {readFile, readdir, writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const assets = {};
for (const directory of ['data', 'data/prompts']) {
  for (const name of (await readdir(`${root}${directory}`)).sort()) {
    if (!/\.(json|txt)$/.test(name)) continue;
    const path = `${directory}/${name}`;
    assets[path] = await readFile(`${root}${path}`, 'utf8');
  }
}

const result = await build({
  absWorkingDir: root,
  entryPoints: ['app.js'],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  write: false,
  define: {
    PRISM_BUNDLED_ASSETS: JSON.stringify(assets),
    process: 'undefined',
    // Only the discarded Node filesystem fallback uses import.meta.url.
    'import.meta.url': 'undefined',
  },
  banner: {js: '/* Generated by npm run build. Edit source files, then rebuild. */'},
});
const output = result.outputFiles[0].contents;
await writeFile(`${root}app.bundle.js`, output);
const revision = createHash('sha256').update(output).digest('hex').slice(0, 12);
const html = await readFile(`${root}index.html`, 'utf8');
const script = /<script\b[^>]*src="\.\/app(?:\.bundle)?\.js[^"\s]*"[^>]*><\/script>/;
if (!script.test(html)) throw Error('Could not find the application script in index.html.');
await writeFile(`${root}index.html`, html.replace(script, `<script defer src="./app.bundle.js?v=${revision}"></script>`));
console.log(`Built app.bundle.js (${output.length} bytes), revision ${revision}`);
